"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, AudioLines, Check, Fingerprint, Flower2, Globe2, Hexagon, Leaf, Menu, ScanLine, ShieldCheck, Sprout, WifiOff, X } from "lucide-react";
import { Brand, BeeMark, HoneyArt } from "@/components/brand";
import { TweakPanel } from "@/components/tweak-panel";
import { LanguageCloud } from "@/components/language-cloud";

const experiences = [
  { name: "For beekeepers", icon: Sprout, title: "Small hives.\nLimitless possibilities.", text: "Your field companion, from the first inspection to the next harvest. Capture work offline, get guidance in your language, and find a market for more of what your hives make.", features: ["Signed offline harvest records", "Provider-backed Indian language guidance", "Honey and beeswax inventory"], view: "hives" },
  { name: "For partners", icon: Hexagon, title: "A connected journey.\nA shared standard.", text: "Bring beekeepers, FPOs, laboratories and processors onto one accountable journey. Reconcile quantities, record custody and put evidence behind every batch.", features: ["Lot genealogy and mass balance", "Laboratory evidence and custody", "Structured buyer requirements"], view: "lots" },
  { name: "For everyone", icon: Fingerprint, title: "Every jar has\na story to tell.", text: "Meet the origin behind the label. A simple scan opens a Honey Passport with the journey, available evidence and current safety status — no account needed.", features: ["A unique identity for each jar", "Accessible origin and evidence", "Live hold and recall status"], view: "passport" },
];

export default function HomePage() {
  const [active, setActive] = useState(0);
  const [menu, setMenu] = useState(false);
  const [serial, setSerial] = useState("BHR-2026-0001");
  const experience = experiences[active];
  return <>
    <header className="site-header"><Brand /><nav className={menu ? "site-nav is-open" : "site-nav"} aria-label="Main navigation"><a href="#ecosystem" onClick={() => setMenu(false)}>The ecosystem</a><a href="#how-it-works" onClick={() => setMenu(false)}>How it works</a><a href="#madhu" onClick={() => setMenu(false)}>Meet Madhu <span className="nav-new">VOICE</span></a><Link href="/passport/BHR-2026-0001">Trace a jar <ArrowUpRight size={14} /></Link></nav><Link className="button button-dark header-cta" href="/workspace">Enter workspace <ArrowUpRight size={15} /></Link><button className="mobile-menu icon-button" onClick={() => setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu ? <X /> : <Menu />}</button></header>
    <main id="main">
      <section className="hero section-shell">
        <div className="hero-copy"><div className="eyebrow"><span className="tiny-dot" /> THE CONNECTED HIVE ECONOMY</div><h1>A sweeter future.<br />Rooted in <span className="serif-word">trust.</span></h1><p>For the hands that nurture every hive.<br />For the stories behind every jar.<br />A little nature. A lot more certainty.</p><div className="hero-actions"><Link href="/workspace" className="button button-dark">Explore Bhramari <ArrowUpRight size={17} /></Link><Link href="/passport/BHR-2026-0001" className="text-link"><ScanLine size={18} /> Trace your honey <ArrowRight size={16} /></Link></div><div className="hero-footnote"><span className="mini-bee"><BeeMark /></span><span>Made for India&apos;s beekeepers.<br /><strong>Built for everyone who believes in them.</strong></span></div></div>
        <div className="hero-visual"><HoneyArt /><div className="floating-proof"><div className="proof-icon"><Fingerprint size={23} /></div><div><span className="micro-label">FROM HIVE TO HOME</span><strong>One journey. Accountable proof.</strong><span className="proof-caption">Discover the Honey Passport <ArrowUpRight size={13} /></span></div></div></div>
        <a className="hero-scroll" href="#ecosystem"><ArrowDown size={15} /> A better world, one hive at a time</a>
      </section>
      <div className="promise-strip"><span><Flower2 /> BEEKEEPER FIRST</span><span><WifiOff /> OFFLINE BY NATURE</span><span><ShieldCheck /> EVIDENCE YOU CAN FOLLOW</span><span><Leaf /> MORE FROM EVERY HIVE</span></div>
      <section id="ecosystem" className="ecosystem section-shell section-pad">
        <div className="section-heading"><div><span className="eyebrow">A WHOLE WORLD AROUND THE HIVE</span><h2>Better, <span className="serif-word">together.</span></h2></div><p>From the quiet work in the field to the honey on your table.<br />One connected ecosystem. Every participant matters.</p></div>
        <div className="experience-tabs" role="tablist" aria-label="Explore Bhramari roles">{experiences.map((item, index) => <button key={item.name} role="tab" aria-selected={active === index} aria-controls="experience-panel" id={`experience-tab-${index}`} onClick={() => setActive(index)} className={active === index ? "active" : ""}><item.icon size={19} />{item.name}<ArrowUpRight size={17} /></button>)}</div>
        <div className="experience-panel" id="experience-panel" role="tabpanel" aria-labelledby={`experience-tab-${active}`}><div className="experience-text" key={active}><span className="chapter-number">0{active + 1} / THE BHRAMARI ECOSYSTEM</span><h3>{experience.title}</h3><p>{experience.text}</p><ul>{experience.features.map(feature => <li key={feature}><Check size={15} />{feature}</li>)}</ul><Link className="text-link" href={active === 2 ? "/passport/BHR-2026-0001" : `/workspace?view=${experience.view}`}>Discover your workspace <ArrowUpRight size={17} /></Link></div><div className={`experience-art experience-art-${active}`}><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="orbit-ring ring-three" /><div className="hive-sculpture"><div className="hive-roof" /><div className="hive-box"><BeeMark /><span>BHRAMARI</span></div><div className="hive-box hive-box-bottom"><span /><span /></div><div className="hive-base" /><div className="hive-feet" /></div><div className="art-note note-one"><span className="status-dot" /><div><strong>{active === 0 ? "Every observation matters" : active === 1 ? "Keep the journey connected" : "A story you can follow"}</strong><span>{active === 0 ? "Inspect · record · care" : active === 1 ? "Harvest · custody · evidence" : "Origin · journey · proof"}</span></div></div><div className="art-note note-two"><Hexagon size={17} /><span>Nature meets a little technology.</span></div></div></div>
      </section>
      <section id="how-it-works" className="journey-section section-shell section-pad"><div className="section-heading"><div><span className="eyebrow">FOLLOW THE GOLDEN THREAD</span><h2>Good honey.<br />An even better <span className="serif-word">story.</span></h2></div><p>Capture locally. Verify collaboratively.<br />Anchor permanently. Explain simply.</p></div><div className="journey-steps">{[{ Icon: Sprout, name: "It begins with a hive", copy: "A registered hive, a caring beekeeper, and a harvest recorded — even without a signal." }, { Icon: ShieldCheck, name: "Every hand accountable", copy: "Custody, quantity and laboratory evidence keep the journey connected and reviewable." }, { Icon: Fingerprint, name: "Proof travels with it", copy: "Cryptographic records make accepted events tamper-evident. Your jar carries its own identity." }, { Icon: ScanLine, name: "The story is yours", copy: "Scan. Explore. Listen. See the origin, the evidence and the latest safety status." }].map(({ Icon, name, copy }, i) => <article className="journey-step" key={name}><div className="step-top"><Icon size={27} strokeWidth={1.3} /><span>0{i + 1}</span></div><h3>{name}</h3><p>{copy}</p></article>)}</div><p className="truth-note">Trust has boundaries. Blockchain protects the integrity of records; laboratory evidence and authorised people assess quality and safety.</p></section>
      <section id="madhu" className="madhu-section section-shell"><div className="madhu-visual"><div className="voice-orb"><AudioLines size={56} strokeWidth={1.1} /></div><div className="soundwave">{Array.from({ length: 47 }, (_, index) => <span key={index} style={{ height: `${Math.round((8 + Math.sin(index * 1.6) ** 2 * (index > 9 && index < 38 ? 55 : 18)) * 100) / 100}px`, animationDelay: `${index * .07}s` }} />)}</div><LanguageCloud compact /></div><div className="madhu-copy"><span className="eyebrow"><AudioLines size={15} /> MEET MADHU, YOUR HIVE COMPANION</span><h2>A familiar voice.<br />A helping <span className="serif-word">hand.</span></h2><p>Speak naturally. Record a harvest. Understand a hive alert. Find your next buyer. Madhu reads current provider capabilities and helps in your selected Indian language.</p><Link href="/workspace?view=madhu" className="button button-dark">Say hello to Madhu <ArrowUpRight size={17} /></Link><span className="subtle-note">Guidance with sources. Actions with your confirmation.</span></div></section>
      <section className="passport-cta section-shell section-pad"><div><span className="eyebrow">A LITTLE CURIOSITY GOES A LONG WAY</span><h2>What&apos;s in <span className="serif-word">your jar?</span></h2><p>Discover its origin. Follow its journey. Check its evidence.</p></div><form className="serial-form" action={`/passport/${encodeURIComponent(serial.trim())}`}><label htmlFor="serial">Enter your bottle serial</label><div><ScanLine size={21} /><input id="serial" name="serial" value={serial} onChange={e => setSerial(e.target.value)} required maxLength={80} pattern="[A-Za-z0-9-]+" /><button type="submit" aria-label="Open Honey Passport"><ArrowRight size={21} /></button></div><span>No login. No wallet. Just the story.</span></form></section>
    </main><footer className="site-footer section-shell"><div><Brand /><p>A connected future, rooted in nature.</p></div><div className="footer-links"><Link href="/workspace">The workspace <ArrowUpRight size={14} /></Link><Link href="/passport/BHR-2026-0001">Honey Passport <ArrowUpRight size={14} /></Link><a href="#how-it-works">Our approach <ArrowUpRight size={14} /></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Bhramari</span><span><Globe2 size={14} /> Grown with purpose in India</span><span>SIH26021 · Working toward a better hive economy</span></div></footer><TweakPanel />
  </>;
}
