"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, Check, CloudUpload, Fingerprint, Hexagon, Plus, ShieldCheck, WifiOff } from "lucide-react";
import { api, display, quantity, shortDate, type Hive, type Lot, type RecordData, type User } from "@/lib/api";
import { FieldVault, type QueueItem } from "@/lib/vault";
import { ActionForm, Empty, ErrorNotice, RecordList, Status, TechnicalDetails, gramField, productOptions, useRecords } from "./workspace-ui";

export function Overview({ user, navigate }: { user: User; navigate: (view: string) => void }) {
  const { data: hives } = useRecords<Hive[]>("/hives");
  const { data: lots, error } = useRecords<Lot[]>("/lots");
  const available = lots?.reduce((sum, lot) => sum + lot.available_g, 0) || 0;
  return <div className="view-stack"><section className="welcome-banner in-gold"><div><span className="marker">Your connected hive economy</span><h2>Good things begin<br />with a little care.</h2><p>Keep your hives healthy, your records connected,<br />and the next chapter of your harvest moving.</p><button className="btn btn-primary" onClick={() => navigate("hives")}><Plus size={16} />Record a harvest</button></div><div className="welcome-hex"><Hexagon size={160} strokeWidth={.65} /><Fingerprint size={75} strokeWidth={.8} /></div></section>{error && <ErrorNotice message={error} />}<div className="stats-grid"><Metric label="Registered hives" value={hives ? String(hives.length) : "—"} note="Your organisation's apiaries" /><Metric label="Available inventory" value={lots ? quantity(available) : "—"} note="Across honey and beeswax" /><Metric label="Traceable lots" value={lots ? String(lots.length) : "—"} note="Accountable lot identities" /><Metric label="Restricted lots" value={lots ? String(lots.filter(lot => ["held", "recalled"].includes(lot.status)).length) : "—"} note="Holds and recalls need attention" /></div><div className="overview-grid"><section className="data-panel"><div className="panel-toolbar"><h3>From your hives</h3><button className="link" onClick={() => navigate("lots")}>All lots <ArrowUpRight size={15} /></button></div>{lots?.length ? lots.slice(0, 5).map(lot => <div className="inventory-row" key={lot.id}><div className="lot-glyph"><Hexagon size={22} /></div><div><strong>{lot.code}</strong><span>{lot.floral} · {lot.product}</span></div><strong>{quantity(lot.available_g)}</strong><Status value={lot.status} /></div>) : <Empty />}</section><section className="next-step-panel in-gold"><span className="marker">A good next step</span><ShieldCheck size={35} strokeWidth={1.2} /><h3>Let your records<br />travel with your harvest.</h3><p>Register this device to capture encrypted, signed records when connectivity drops.</p><button className="link" onClick={() => navigate("queue")}>Set up your field vault <ArrowUpRight size={16} /></button></section></div></div>;
}

function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>; }

export function HivesView({ user }: { user: User }) {
  const [revision, setRevision] = useState(0);
  const [offline, setOffline] = useState(false);
  const { data: hives } = useRecords<Hive[]>("/hives", revision);
  const hiveOptions = hives?.map(hive => ({ value: hive.id, label: `${hive.name} · ${hive.id}` })) || [{ value: "HIVE-MH-001", label: "Sahyadri hive · HIVE-MH-001" }];
  const changed = () => setRevision(value => value + 1);
  return <div className="view-stack"><RecordList title="Your apiaries" path="/hives" revision={revision} columns={[{ key: "name", label: "Hive" }, { key: "region", label: "Region" }, { key: "floral", label: "Floral source" }, { key: "status", label: "Condition", render: value => <Status value={value} /> }]} /><div className="mode-banner"><WifiOff size={19} /><div><strong>Offline field capture</strong><p>Save signed records in your encrypted browser vault. Enable your device in the sync queue first.</p></div><label className="toggle-label"><input type="checkbox" checked={offline} onChange={event => setOffline(event.target.checked)} />Save locally</label></div><div className="form-grid"><ActionForm title="Record a harvest" description={offline ? "Signed and saved locally. Sync when you reconnect." : "Create an accountable source lot from a registered hive."} fields={[{ name: "hive_id", label: "Source hive", options: hiveOptions }, { name: "product", label: "Hive product", options: productOptions }, gramField, { name: "floral", label: "Floral source", value: "Multiflora" }, { name: "notes", label: "Field notes", type: "textarea", required: false }]} submit={async data => { const payload = { ...data, quantity_g: Number(data.quantity_g) }; return offline ? FieldVault.capture(user, "harvest", data.hive_id, payload) : api.post("/lots/harvest", payload); }} onSuccess={changed} action={offline ? "Sign & save offline" : "Create harvest lot"} /><ActionForm title="Inspect a hive" description="A useful observation today helps care for tomorrow." fields={[{ name: "hive_id", label: "Hive", options: hiveOptions }, { name: "status", label: "Observed condition", options: ["healthy", "attention", "urgent"].map(value => ({ value, label: value })) }, { name: "frames", label: "Frames inspected", type: "number", value: 8, min: 0, max: 100, step: 1 }, { name: "queen_seen", label: "Queen observed", options: [{ value: "true", label: "Yes" }, { value: "false", label: "No / not observed" }] }, { name: "observation", label: "Observation", type: "textarea" }]} submit={data => { const payload = { status: data.status, frames: Number(data.frames), queen_seen: data.queen_seen === "true", observation: data.observation }; return offline ? FieldVault.capture(user, "inspection", data.hive_id, payload) : api.post(`/hives/${data.hive_id}/inspections`, payload); }} onSuccess={changed} action={offline ? "Sign & save inspection" : "Save inspection"} /></div><ActionForm title="Register a hive" fields={[{ name: "name", label: "Hive name" }, { name: "region", label: "Region", value: "Pune, Maharashtra" }, { name: "floral", label: "Floral source", value: "Multiflora" }]} submit={data => api.post("/hives", data)} onSuccess={changed} /></div>;
}

export function QueueView({ user }: { user: User }) {
  const [items, setItems] = useState<QueueItem[]>([]);
  const [ready, setReady] = useState(false);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const refresh = async () => { setItems(await FieldVault.list(user)); setReady(await FieldVault.ready(user)); };
  useEffect(() => { refresh().catch(failure => setError(failure.message)); }, [user.id]); // Device state belongs to the signed-in actor.
  async function act(provision: boolean) {
    setBusy(true); setError(""); setNotice("");
    try { if (provision) { await FieldVault.provision(user); setNotice("Device registered. You can now capture offline."); } else { const accepted = await FieldVault.sync(user); setNotice(`${accepted} record(s) accepted. Anchor status is tracked separately by the ledger.`); } await refresh(); } catch (failure) { setError(failure instanceof Error ? failure.message : "Vault action failed."); } finally { setBusy(false); }
  }
  return <div className="view-stack"><section className="vault-banner in-gold"><Fingerprint size={55} strokeWidth={1.1} /><div><span className="marker">CAPTURE LOCALLY. SYNC WITH CONFIDENCE.</span><h2>Your secure field vault</h2><p>AES-GCM encrypted records. Ed25519 device signatures.<br />Your queue stays in this browser when you close the page.</p></div><button className="btn btn-primary" disabled={busy} onClick={() => act(!ready)}>{ready ? <CloudUpload size={17} /> : <ShieldCheck size={17} />}{ready ? "Sync pending records" : "Enable this device"}</button></section>{notice && <div className="notice notice-success" role="status"><Check size={17} />{notice}</div>}{error && <ErrorNotice message={error} />}<section className="data-panel"><div className="panel-toolbar"><h3>Local records <span className="count-badge">{items.length}</span></h3><Status value={ready ? "device ready" : "setup required"} /></div>{!items.length ? <Empty>No local records yet. Open Hives & harvest and turn on “Save locally”.</Empty> : <div className="table-scroll"><table><thead><tr><th>Sequence</th><th>Event</th><th>Captured</th><th>Sync status</th><th>Receipt</th></tr></thead><tbody>{items.map(item => <tr key={item.event_id}><td>#{item.sequence}</td><td className="mono">{item.event_id.slice(0, 18)}…</td><td>{shortDate(item.created_at)}</td><td><Status value={item.status} /></td><td>{item.receipt ? <TechnicalDetails data={item.receipt} label="Receipt" /> : "Awaiting sync"}</td></tr>)}</tbody></table></div>}</section><div className="notice"><ShieldCheck size={20} /><p>Rejected and disputed records remain reviewable. Browser storage is specific to this device and origin; clearing site data removes this local vault. Sync accepted records before changing devices.</p></div></div>;
}
