"use client";

import { useState } from "react";
import { Activity, CalendarDays, CircleAlert, Handshake, PhoneCall, Radio, Users } from "lucide-react";
import { api, display, quantity, type Hive, type RecordData, type User } from "@/lib/api";
import { ActionForm, Empty, ErrorNotice, RecordList, Status, TechnicalDetails, gramField, productOptions, useRecords } from "./workspace-ui";

export function MarketView({ user }: { user: User }) {
  const [revision, setRevision] = useState(0); const [matches, setMatches] = useState<RecordData | null>(null); const [error, setError] = useState("");
  const { data: requirements } = useRecords<RecordData[]>("/market/requirements", revision);
  const canRequest = ["buyer", "processor", "fpo", "admin"].includes(user.role);
  async function find(id: string) { try { setMatches(await api.get(`/market/requirements/${id}/matches`)); } catch (failure) { setError((failure as Error).message); } }
  return <div className="view-stack"><div className="notice"><Handshake size={21} /><p>Matches filter compliance and available quantity first. New and small suppliers receive an initial exposure position.</p></div>{error && <ErrorNotice message={error} />}{canRequest && <ActionForm title="Publish a buyer requirement" description="Bhramari ends at an accountable enquiry, quotation and order status." fields={[{ name: "product", label: "Product", options: productOptions }, gramField, { name: "region", label: "Origin preference", value: "Maharashtra", required: false }, { name: "floral", label: "Floral preference", required: false }, { name: "max_moisture", label: "Maximum moisture (%)", type: "number", min: 0, max: 100, step: .1, value: 18.5, required: false }, { name: "delivery_by", label: "Delivery by", type: "date", required: false }, { name: "packaging", label: "Packaging", value: "Food-safe bulk containers" }, { name: "terms", label: "Terms", type: "textarea", value: "Sample before quotation" }]} submit={data => api.post("/market/requirements", { ...data, quantity_g: Number(data.quantity_g), max_moisture: data.max_moisture ? Number(data.max_moisture) : null, delivery_by: data.delivery_by || null })} onSuccess={() => setRevision(value => value + 1)} action="Publish requirement" />}
    <section className="data-panel"><div className="panel-toolbar"><h3>Open buyer requirements</h3></div>{requirements?.length ? requirements.map(item => <div className="inventory-row" key={display(item.id)}><div className="lot-glyph"><Handshake size={20} /></div><div><strong>{display(item.product)}</strong><span>{quantity(Number(item.quantity_g))} · {display(item.region)}</span></div><Status value={item.status} /><button className="link" onClick={() => find(display(item.id))}>Find supply</button></div>) : <Empty />}</section>
    {matches && <section className="data-panel"><div className="panel-toolbar"><h3>Evidence-complete supply</h3><span>{display(matches.policy)}</span></div>{(matches.matches as RecordData[]).map(item => <div className="inventory-row" key={display(item.lot_id)}><div><strong>{display(item.code)}</strong><span>{display(item.region)} · {quantity(Number(item.available_g))}</span></div><span>{(item.reasons as string[]).join(" · ")}</span><button className="btn btn-primary btn-sm" onClick={async () => { await api.post("/market/enquiries", { requirement_id: matches.requirement_id, lot_id: item.lot_id, message: "Please share a quotation and sample availability." }); setRevision(value => value + 1); }}>Enquire</button></div>)}</section>}
    <RecordList title="Enquiries and quotations" path="/market/enquiries" revision={revision} columns={[{ key: "lot_id", label: "Supply lot" }, { key: "quantity_g", label: "Quantity", render: value => quantity(Number(value)) }, { key: "status", label: "Status", render: value => <Status value={value} /> }, { key: "quote_minor", label: "Quote (₹)", render: value => value ? `₹${(Number(value) / 100).toLocaleString("en-IN")}` : "—" }]} /></div>;
}

export function CirclesView() {
  const [revision, setRevision] = useState(0); const { data: equipment } = useRecords<RecordData[]>("/circles/equipment", revision);
  return <div className="view-stack"><section className="welcome-banner compact in-gold"><div><span className="marker">Sahyadri bee circle</span><h2>Learn together.<br />Share what helps.</h2><p>Moderated support, mentor requests and shared equipment. Assurance comes from evidence and resolved work, not popularity.</p></div><Users size={105} strokeWidth={.8} /></section><div className="form-grid"><ActionForm title="Request a mentor" fields={[{ name: "hive_id", label: "Hive ID", required: false }, { name: "question", label: "What support do you need?", type: "textarea" }]} submit={data => api.post("/circles/mentor-requests", { ...data, hive_id: data.hive_id || null })} onSuccess={() => setRevision(value => value + 1)} action="Request a callback" /><ActionForm title="Ask the circle" fields={[{ name: "circle_id", label: "Circle", value: "sahyadri" }, { name: "question", label: "Question", type: "textarea" }]} submit={data => api.post("/circles/questions", data)} onSuccess={() => setRevision(value => value + 1)} action="Submit for moderation" /></div><RecordList title="Mentor requests" path="/circles/mentor-requests" revision={revision} columns={[{ key: "question", label: "Request" }, { key: "hive_id", label: "Hive" }, { key: "status", label: "Status", render: value => <Status value={value} /> }]} />{equipment?.length && <ActionForm title="Book shared equipment" description={display(equipment[0].name)} fields={[{ name: "equipment_id", label: "Equipment", options: equipment.map(item => ({ value: display(item.id), label: display(item.name) })) }, { name: "starts_at", label: "Start", type: "datetime-local" }, { name: "ends_at", label: "End", type: "datetime-local" }]} submit={data => api.post("/circles/bookings", { ...data, starts_at: new Date(data.starts_at).toISOString(), ends_at: new Date(data.ends_at).toISOString() })} onSuccess={() => setRevision(value => value + 1)} action="Book equipment" />}<RecordList title="Equipment bookings" path="/circles/bookings" revision={revision} columns={[{ key: "equipment_id", label: "Equipment" }, { key: "starts_at", label: "Start" }, { key: "ends_at", label: "End" }, { key: "status", label: "Status", render: value => <Status value={value} /> }]} /></div>;
}

export function SensorsView() {
  const [revision, setRevision] = useState(0); const { data: hives } = useRecords<Hive[]>("/hives"); const options = hives?.map(item => ({ value: item.id, label: item.name })) || [];
  return <div className="view-stack"><div className="notice"><Radio size={21} /><p>Sensor analytics detect early risk patterns and route them to a human inspection. They do not diagnose disease or prescribe treatment.</p></div><div className="form-grid"><ActionForm title="Record a sensor reading" fields={[{ name: "hive_id", label: "Hive", options }, { name: "temperature_c", label: "Temperature (°C)", type: "number", value: 34, min: -40, max: 85, step: .1 }, { name: "humidity_pct", label: "Humidity (%)", type: "number", value: 58, min: 0, max: 100, step: .1 }, { name: "weight_kg", label: "Hive weight (kg)", type: "number", value: 28, min: 0, max: 500, step: .01 }]} submit={data => api.post("/sensors/readings", { ...data, temperature_c: Number(data.temperature_c), humidity_pct: Number(data.humidity_pct), weight_kg: Number(data.weight_kg), recorded_at: new Date().toISOString() })} onSuccess={() => setRevision(value => value + 1)} /><ActionForm title="Run deterministic demo feed" description="Clearly marked simulation for a repeatable SIH demonstration." fields={[{ name: "hive_id", label: "Hive", options }, { name: "scenario", label: "Scenario", options: ["normal", "heat", "brood_risk", "weight_drop", "stuck", "productivity"].map(value => ({ value, label: value.replace("_", " ") })) }]} submit={data => api.post("/sensors/simulate", data)} onSuccess={() => setRevision(value => value + 1)} action="Run simulator" /></div><RecordList title="Disease-risk and productivity screening" path="/sensors/analytics?reserve_weight_kg=20" revision={revision} columns={[{ key: "hive_name", label: "Hive" }, { key: "disease_risk", label: "Risk screen", render: value => <Status value={value} /> }, { key: "risk_categories", label: "Detected patterns", render: value => Array.isArray(value) && value.length ? value.map(display).join(", ") : "None" }, { key: "health_score", label: "Health score" }, { key: "harvestable_kg", label: "Current surplus", render: value => value === null ? "—" : `${display(value)} kg` }, { key: "predicted_harvestable_kg", label: "7-day forecast", render: value => value === null ? "Need 24h history" : `${display(value)} kg` }, { key: "forecast_confidence", label: "Forecast confidence", render: value => <Status value={value} /> }, { key: "recommendation", label: "Recommended action" }]} /><RecordList title="Explainable alerts" path="/sensors/alerts" revision={revision} columns={[{ key: "hive_id", label: "Hive" }, { key: "rule", label: "Rule" }, { key: "explanation", label: "Why it fired" }, { key: "confidence", label: "Confidence" }, { key: "status", label: "Status", render: value => <Status value={value} /> }]} /></div>;
}

export function AssistedView() {
  const [revision, setRevision] = useState(0); const [created, setCreated] = useState<RecordData | null>(null); const { data: farmers } = useRecords<RecordData[]>("/assisted/farmers", revision);
  const farmer = farmers?.[0]; const hives = (farmer?.hives as RecordData[] | undefined) || [];
  return <div className="view-stack"><div className="notice"><PhoneCall size={21} /><p>This simulates call or SMS intake through an authorized FPO agent. The farmer confirms with a Farmer Card PIN; production voice and OTP require a connected provider.</p></div><ActionForm title="Capture an assisted request" description="Demo Farmer Card PIN: 2468. The request stores the agent, farmer, channel and consent method." fields={[{ name: "farmer_id", label: "Farmer Card", options: farmers?.map(item => ({ value: display(item.id), label: display(item.name) })) || [] }, { name: "farmer_name", label: "Farmer name", value: display(farmer?.name || "Asha Patil") }, { name: "phone_last4", label: "Phone last four digits", value: "7742" }, { name: "language", label: "Language code", value: "hi-IN" }, { name: "request_type", label: "Request", options: [{ value: "harvest", label: "Record harvest" }, { value: "mentor", label: "Mentor callback" }, { value: "buyer", label: "Buyer support" }] }, { name: "hive_id", label: "Hive", options: hives.map(item => ({ value: display(item.id), label: display(item.name) })) }, gramField]} submit={async data => { const result = await api.post<RecordData>("/assisted/requests", { ...data, quantity_g: Number(data.quantity_g) }); setCreated(result); return result; }} onSuccess={() => setRevision(value => value + 1)} action="Create pending request" />{created && <ActionForm title="Farmer confirmation" description={`Pending request ${display(created.id)}`} fields={[{ name: "confirmation", label: "Farmer Card PIN", type: "password" }]} submit={data => api.post(`/assisted/requests/${display(created.id)}/confirm`, { consent_method: "pin", confirmation: data.confirmation })} onSuccess={value => { setCreated(value as RecordData); setRevision(rev => rev + 1); }} action="Confirm with farmer" />}<RecordList title="Assisted access audit" path="/assisted/requests" revision={revision} columns={[{ key: "farmer_name", label: "Farmer" }, { key: "request_type", label: "Request" }, { key: "capture_mode", label: "Capture" }, { key: "status", label: "Status", render: value => <Status value={value} /> }]} /></div>;
}

export function ControlView() {
  const { data, error, refresh } = useRecords<RecordData>("/control"); if (error) return <ErrorNotice message={error} retry={refresh} />; if (!data) return <div className="loading-row"><Activity className="spin" />Loading control tower…</div>;
  const metrics = data.metrics as RecordData; const audit = data.audit_kpis as RecordData; const exceptions = data.exceptions as RecordData[];
  return <div className="view-stack"><div className="stats-grid">{Object.entries(metrics).map(([key, value]) => <div className="metric" key={key}><span>{key.replaceAll("_", " ")}</span><strong>{display(value)}</strong><small>Live scoped projection</small></div>)}</div><section className="data-panel"><div className="panel-toolbar"><h3>Audit KPIs</h3></div><div className="stats-grid">{Object.entries(audit).map(([key, value]) => <div className="metric" key={key}><span>{key.replaceAll("_", " ")}</span><strong>{value === null ? "No data" : key.endsWith("_pct") ? `${display(value)}%` : display(value)}</strong></div>)}</div></section><section className="data-panel"><div className="panel-toolbar"><h3>Exception queue</h3><button className="icon-btn" onClick={refresh}><Activity size={16} /></button></div>{exceptions.length ? exceptions.map(item => <div className="exception-row" key={`${display(item.type)}-${display(item.id)}`}><CircleAlert size={20} /><div><strong>{display(item.title)}</strong><span>{display(item.detail)}</span></div><Status value={item.severity} /></div>) : <Empty>No active exceptions in your scope.</Empty>}</section><ActionForm title="Resolve a dispute" description="Claim the review first, then record a final resolution." fields={[{ name: "dispute_id", label: "Dispute ID" }, { name: "status", label: "Next state", options: [{ value: "under_review", label: "Under review" }, { value: "resolved", label: "Resolved" }, { value: "rejected", label: "Rejected" }] }, { name: "resolution", label: "Resolution", type: "textarea", required: false }]} submit={data => api.patch(`/disputes/${data.dispute_id}`, { status: data.status, resolution: data.resolution })} onSuccess={refresh} action="Update dispute" /><TechnicalDetails data={data} label="Audit projection and claim boundaries" /></div>;
}
